.TH ALIGN_GREENGENES 1 2021-11-25 "" "align_greengenes"
.SH NAME
align_greengenes \- align_greengenes()
.SH SYNOPSIS
\fIalign_greengenes()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.align_greengenes at ncbi_taxonomy.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
