.TH ALIGN.SEQS 1 2021-11-25 "" "align.seqs"
.SH NAME
align.seqs \- align.seqs(contigs, silva, num_threads = 8)
.SH SYNOPSIS
\fIalign.seqs(contigs, silva, num_threads = 8)\fR
.SH OPTIONS
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBsilva\fB \fR\- . 
.PP
.PP
\fBnum_threads\fB \fR\- 8. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.align.seqs at mothur.R:line 164
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
