.TH ALIGN_SILVA 1 2021-12-13 "" "align_silva"
.SH NAME
align_silva \- align_silva(blastn = getOption(ncbi_blast))
.SH SYNOPSIS
\fIalign_silva(blastn = getOption(ncbi_blast))\fR
.SH OPTIONS
.PP
\fBblastn\fB \fR\- getOption(ncbi_blast). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.align_silva at taxonomy.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
