.TH ANALYSIS_MICROBIOME 1 2026-5月 "" "analysis_microbiome"
.SH NAME
analysis_microbiome \- analysis_microbiome(otu.table, sampleinfo, output.dir)
.SH SYNOPSIS
\fIanalysis_microbiome(otu.table, sampleinfo, output.dir)\fR
.SH OPTIONS
.PP
\fBotu.table\fB \fR\- . 
.PP
.PP
\fBsampleinfo\fB \fR\- . 
.PP
.PP
\fBoutput.dir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.analysis_microbiome at analysis_microbiome.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2026
