.TH BIN.SEQS 1 2021-12-13 "" "``bin.seqs`` prints out a fasta-formatted file where sequences are ordered according to the OTU that they belong to. Such an output may be helpful for generating primers specific to an OTU or for classification of sequences."
.SH NAME
bin.seqs \- bin.seqs(list, contigs, contig.names, logfile = [12]bin.seqs.txt)
.SH SYNOPSIS
\fIbin.seqs(list, contigs, contig.names, logfile = [12]bin.seqs.txt)\fR
.SH OPTIONS
.PP
\fBlist\fB \fR\- . 
.PP
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBcontig.names\fB \fR\- . 
.PP
.PP
\fBlogfile\fB \fR\- [12]bin.seqs.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.bin.seqs at mothur.R:line 310
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
