.TH BIN.SEQS 1 2021-11-25 "" "bin.seqs"
.SH NAME
bin.seqs \- bin.seqs(list, contigs, contig.names)
.SH SYNOPSIS
\fIbin.seqs(list, contigs, contig.names)\fR
.SH OPTIONS
.PP
\fBlist\fB \fR\- . 
.PP
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBcontig.names\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.bin.seqs at mothur.R:line 211
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
