.TH CLUSTER 1 2021-11-25 "" "cluster"
.SH NAME
cluster \- cluster(dist, method = furthest, cutoff = 0.03, num_threads = 32, logfile = [11]cluster.txt)
.SH SYNOPSIS
\fIcluster(dist, method = furthest, cutoff = 0.03, num_threads = 32, logfile = [11]cluster.txt)\fR
.SH OPTIONS
.PP
\fBdist\fB \fR\- . 
.PP
.PP
\fBmethod\fB \fR\- furthest. 
.PP
.PP
\fBcutoff\fB \fR\- 0.03. 
.PP
.PP
\fBnum_threads\fB \fR\- 32. 
.PP
.PP
\fBlogfile\fB \fR\- [11]cluster.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.cluster at mothur.R:line 203
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
