.TH COUNT.SEQS 1 2021-11-25 "" "count.seqs"
.SH NAME
count.seqs \- count.seqs(names, groups)
.SH SYNOPSIS
\fIcount.seqs(names, groups)\fR
.SH OPTIONS
.PP
\fBnames\fB \fR\- . 
.PP
.PP
\fBgroups\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.count.seqs at mothur.R:line 155
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
