.TH DIST.SEQS 1 2021-12-08 "" "The dist.seqs command will calculate uncorrected pairwise distances between aligned DNA sequences. This approach is better than the commonly used DNADIST because the distances are not stored in RAM, rather they are printed directly to a file. Furthermore, it is possible to ignore “large” distances that one might not be interested in. The command will generate a column-formatted distance matrix that is compatible with the column option in the various cluster commands. The command is also able to generate a phylip-formatted distance matrix."
.SH NAME
dist.seqs \- dist.seqs(align_fasta, calc = onegap, countends = F, cutoff = 0.03, output = lt, num_threads = 32, logfile = [10]dist.seqs.txt)
.SH SYNOPSIS
\fIdist.seqs(align_fasta, calc = onegap, countends = F, cutoff = 0.03, output = lt, num_threads = 32, logfile = [10]dist.seqs.txt)\fR
.SH OPTIONS
.PP
\fBalign_fasta\fB \fR\- . 
.PP
.PP
\fBcalc\fB \fR\- onegap. 
.PP
.PP
\fBcountends\fB \fR\- F. 
.PP
.PP
\fBcutoff\fB \fR\- 0.03. 
.PP
.PP
\fBoutput\fB \fR\- lt. 
.PP
.PP
\fBnum_threads\fB \fR\- 32. 
.PP
.PP
\fBlogfile\fB \fR\- [10]dist.seqs.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.dist.seqs at mothur.R:line 272
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
