.TH GET.OTUREP 1 2021-12-15 "" "While the bin.seqs command reports the OTU number for all sequences, the ``get.oturep`` command generates a fasta-formatted sequence file containing only a representative sequence for each OTU. A .rep.fasta and .rep.name file or .rep.count_table file is generated for each OTU definition."
.SH NAME
get.oturep \- get.oturep(dist, contig.unique.fasta, list, label = 0.03, logfile = [13]get.oturep.txt)
.SH SYNOPSIS
\fIget.oturep(dist, contig.unique.fasta, list, label = 0.03, logfile = [13]get.oturep.txt)\fR
.SH OPTIONS
.PP
\fBdist\fB \fR\- . 
.PP
.PP
\fBcontig.unique.fasta\fB \fR\- . 
.PP
.PP
\fBlist\fB \fR\- . 
.PP
.PP
\fBlabel\fB \fR\- 0.03. 
.PP
.PP
\fBlogfile\fB \fR\- [13]get.oturep.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get.oturep at mothur.R:line 358
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
