.TH GETBLASTNMAPPING 1 2021-12-15 "" "Parse blastn result text"
.SH NAME
getBlastnMapping \- getBlastnMapping(outTxt)
.SH SYNOPSIS
\fIgetBlastnMapping(outTxt)\fR
.SH OPTIONS
.PP
\fBoutTxt\fB \fR\- . the filepath of the blastn alignment output. function will parse the blastn mapping table result from this data file via GCModeller library.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getBlastnMapping at blast.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
