.TH GREENGENES_OTUTAXONOMY 1 2024-Feb "" "Workflow for 16s"
.SH NAME
greengenes_OTUTaxonomy \- greengenes_OTUTaxonomy(left, right,
    <i>outputdir</i> = ./,
    <i>num.threads</i> = <span style='color: green;'>32</span>,
    <i>evalue</i> = <span style='color: green;'>1E-10</span>,
    <i>make.contigs</i> = list(algorithm = needleman, score = [1, -1, -2, -1], insert = 20),
    <i>skip.mothur</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIgreengenes_OTUTaxonomy(left, right,
    <i>outputdir</i> = ./,
    <i>num.threads</i> = <span style='color: green;'>32</span>,
    <i>evalue</i> = <span style='color: green;'>1E-10</span>,
    <i>make.contigs</i> = list(algorithm = needleman, score = [1, -1, -2, -1], insert = 20),
    <i>skip.mothur</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH DESCRIPTION
.PP
Workflow for create 16s data analysis based on the mothur software and NCBI blastn program. Workflow steps in this function includes: 1. create OTU sequence based on the mothur workflow 2. alignment of the OTU sequence with the greengenes database via NCBI blastn pipeline
.PP
.SH OPTIONS
.PP
\fBleft\fB \fR\- . 
.PP
.PP
\fBright\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBnum.threads\fB \fR\- 32. 
.PP
.PP
\fBevalue\fB \fR\- 1E-10. 
.PP
.PP
\fBmake.contigs\fB \fR\- list(algorithm = needleman, score = [1, -1, -2, -1], insert = 20). the parameters for run short reads assembler function from the mothur program. About the parameter usage notes, reference to the ``make.contigs`` function.
.PP
.PP
\fBskip.mothur\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.greengenes_OTUTaxonomy at greengenes_OTUTaxonomy.R:line 16
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
