.TH GREENGENES_OTUTAXONOMY 1 2021-12-09 "" "Workflow for 16s"
.SH NAME
greengenes_OTUTaxonomy \- greengenes_OTUTaxonomy(left, right, outputdir = ./, num_threads = 32, evalue = 1E-10, skip_mothur = FALSE)
.SH SYNOPSIS
\fIgreengenes_OTUTaxonomy(left, right, outputdir = ./, num_threads = 32, evalue = 1E-10, skip_mothur = FALSE)\fR
.SH DESCRIPTION
.PP
Workflow for create 16s data analysis based on the mothur software and NCBI blastn program. Workflow steps in this function includes: 1. create OTU sequence based on the mothur workflow 2. alignment of the OTU sequence with the greengenes database via NCBI blastn pipeline
.PP
.SH OPTIONS
.PP
\fBleft\fB \fR\- . 
.PP
.PP
\fBright\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBnum_threads\fB \fR\- 32. 
.PP
.PP
\fBevalue\fB \fR\- 1E-10. 
.PP
.PP
\fBskip_mothur\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.greengenes_OTUTaxonomy at greengenes_OTUTaxonomy.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
