.TH GREENGENES_OPTS 1 2021-12-09 "" "parse greengenes option value"
.SH NAME
greengenes_opts \- greengenes_opts()
.SH SYNOPSIS
\fIgreengenes_opts()\fR
.SH VALUE
.PP
a list object that contains two elements: 1. fasta: is the file path of the fasta sequence file 2. taxonomy: is the file path of the taxonomy data for the data annotation of the OTU sequence
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.greengenes_opts at greengenes_OTUTaxonomy.R:line 62
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
