.TH MOTHUR_FILES 1 2022-05-07 "" "Create mothur file list"
.SH NAME
mothur_files \- mothur_files(dir, filename = ./16s.files)
.SH SYNOPSIS
\fImothur_files(dir, filename = ./16s.files)\fR
.SH OPTIONS
.PP
\fBdir\fB \fR\- . a directory path which contains the ``R1/R2`` pair-end fastq sequence file.
.PP
.PP
\fBfilename\fB \fR\- ./16s.files. the file name to save as the 16s file list.
.PP
.SH VALUE
.PP
a character vector of the sample id in the given data directory.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothur_files at pairend.R:line 42
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2022
