.TH MOTHUR_WORKFLOW 1 2021-12-14 "" "commandline workflow for run mothur"
.SH NAME
mothur_workflow \- mothur_workflow(work16s)
.SH SYNOPSIS
\fImothur_workflow(work16s)\fR
.SH OPTIONS
.PP
\fBwork16s\fB \fR\- . the 16s workflow workspace object, contains necessary parameter files.
.PP
.SH DETAILS
.PP
you must change of current work directory to the output directory, due to the reason of all of the data file path in this workflow function is relative path to the result data directory ``outputdir``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothur_workflow at mothur_OTU.R:line 47
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
