.TH MOTHUR_OTU 1 2021-12-09 "" "Build OTU based on mothur"
.SH NAME
mothur_OTU \- mothur_OTU(left, right, refalign, outputdir = ./, num_threads = 32)
.SH SYNOPSIS
\fImothur_OTU(left, right, refalign, outputdir = ./, num_threads = 32)\fR
.SH OPTIONS
.PP
\fBleft\fB \fR\- . the left paired-end sequence file.
.PP
.PP
\fBright\fB \fR\- . the right paired-end sequence file.
.PP
.PP
\fBrefalign\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. the result output dir for save temp file
.PP
.PP
\fBnum_threads\fB \fR\- 32. the number of the processor threads that will be used in the mothur software.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothur_OTU at mothur_OTU.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
