.TH MOTHUR_OTU 1 2024-Feb "" "Build OTU based on mothur"
.SH NAME
mothur_OTU \- mothur_OTU(left, right, refalign,
    <i>outputdir</i> = ./,
    <i>assembler</i> = list(algorithm = needleman, score = [1, -1, -2, -1], insert = 20),
    <i>num.threads</i> = <span style='color: green;'>32</span>)
.SH SYNOPSIS
\fImothur_OTU(left, right, refalign,
    <i>outputdir</i> = ./,
    <i>assembler</i> = list(algorithm = needleman, score = [1, -1, -2, -1], insert = 20),
    <i>num.threads</i> = <span style='color: green;'>32</span>)\fR
.SH OPTIONS
.PP
\fBleft\fB \fR\- . the left paired-end sequence file.
.PP
.PP
\fBright\fB \fR\- . the right paired-end sequence file.
.PP
.PP
\fBrefalign\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. the result output dir for save temp file
.PP
.PP
\fBassembler\fB \fR\- list(algorithm = needleman, score = [1, -1, -2, -1], insert = 20). 
.PP
.PP
\fBnum.threads\fB \fR\- 32. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothur_OTU at mothur_OTU.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
