.TH MOTHUR_OTU 1 2021-12-08 "" "Build OTU based on mothur"
.SH NAME
mothur_OTU \- mothur_OTU(left, right, outputdir = ./, num_threads = 32)
.SH SYNOPSIS
\fImothur_OTU(left, right, outputdir = ./, num_threads = 32)\fR
.SH OPTIONS
.PP
\fBleft\fB \fR\- . 
.PP
.PP
\fBright\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBnum_threads\fB \fR\- 32. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothur_OTU at mothur_OTU.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
