.TH MOTHURERRORPARSER 1 2021-12-13 "" "Parse error message"
.SH NAME
mothurErrorParser \- mothurErrorParser(stdout)
.SH SYNOPSIS
\fImothurErrorParser(stdout)\fR
.SH OPTIONS
.PP
\fBstdout\fB \fR\- . the standard output dumpping text of the mothur program.
.PP
.SH VALUE
.PP
a error message pair list object.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothurErrorParser at commandline.R:line 62
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
