.TH MOTHURARGVS 1 2021-12-09 "" "Create commandline arguments"
.SH NAME
mothurArgvs \- mothurArgvs(argv)
.SH SYNOPSIS
\fImothurArgvs(argv)\fR
.SH OPTIONS
.PP
\fBargv\fB \fR\- . a list object that contains commandline parameters for run a specific mothur command. commandline argument which it has ``NULL`` value will be ignored in this function.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothurArgvs at mothur.R:line 34
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
