.TH MOTHUR_FILES 1 2021-12-14 "" "Create mothur file list"
.SH NAME
mothur_files \- mothur_files(dir, filename = ./16s.files)
.SH SYNOPSIS
\fImothur_files(dir, filename = ./16s.files)\fR
.SH OPTIONS
.PP
\fBdir\fB \fR\- . a directory path which contains the ``R1/R2`` pair-end fastq sequence file.
.PP
.PP
\fBfilename\fB \fR\- ./16s.files. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mothur_files at pairend.R:line 32
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
