.TH PAIRENDS 1 2022-05-07 "" "load pair-end file list"
.SH NAME
pairEnds \- pairEnds(dir)
.SH SYNOPSIS
\fIpairEnds(dir)\fR
.SH OPTIONS
.PP
\fBdir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pairEnds at pairend.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2022
