.TH PAIRENDS 1 2021-12-14 "" "pairEnds"
.SH NAME
pairEnds \- pairEnds(dir)
.SH SYNOPSIS
\fIpairEnds(dir)\fR
.SH OPTIONS
.PP
\fBdir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pairEnds at pairend.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
