.TH RUNMOTHUR 1 2024-Feb "" "the mothur cli wrapper"
.SH NAME
runMothur \- runMothur(command, argv, log)
.SH SYNOPSIS
\fIrunMothur(command, argv, log)\fR
.SH OPTIONS
.PP
\fBcommand\fB \fR\- . the mothur command string.
.PP
.PP
\fBargv\fB \fR\- . 
.PP
.PP
\fBlog\fB \fR\- . the logfile file path.
.PP
.SH DETAILS
.PP
Schloss PD et al. 2009. Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Applied and Environmental Microbiology 75:7537–7541.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.runMothur at commandline.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
