.TH RUNMOTHUR 1 2021-11-25 "" "the mothur cli wrapper"
.SH NAME
runMothur \- runMothur(command, argv, log)
.SH SYNOPSIS
\fIrunMothur(command, argv, log)\fR
.SH OPTIONS
.PP
\fBcommand\fB \fR\- . the mothur command string.
.PP
.PP
\fBargv\fB \fR\- . 
.PP
.PP
\fBlog\fB \fR\- . the logfile file path.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.runMothur at mothur.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
