.TH SCREEN.SEQS 1 2024-Feb "" "RunAutoScreen"
.SH NAME
screen.seqs \- screen.seqs(contigs,
    <i>num.threads</i> = <span style='color: green;'>8</span>)
.SH SYNOPSIS
\fIscreen.seqs(contigs,
    <i>num.threads</i> = <span style='color: green;'>8</span>)\fR
.SH DESCRIPTION
.PP
The screen.seqs command enables you to keep sequences that fulfill certain user defined criteria. Furthermore, it enables you to cull those sequences not meeting the criteria from a names, group, contigsreport, alignreport and summary file.
.PP
.SH OPTIONS
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBnum.threads\fB \fR\- 8. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.screen.seqs at mothur.R:line 130
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
