.TH SCREEN.SEQS 1 2021-12-10 "" "RunAutoScreen"
.SH NAME
screen.seqs \- screen.seqs(contigs, num_threads = 8)
.SH SYNOPSIS
\fIscreen.seqs(contigs, num_threads = 8)\fR
.SH DESCRIPTION
.PP
The screen.seqs command enables you to keep sequences that fulfill certain user defined criteria. Furthermore, it enables you to cull those sequences not meeting the criteria from a names, group, contigsreport, alignreport and summary file.
.PP
.SH OPTIONS
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBnum_threads\fB \fR\- 8. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.screen.seqs at mothur.R:line 84
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
