.TH SPLIT.GROUPS 1 2022-05-07 "" "count for groups"
.SH NAME
split.groups \- split.groups(fasta, group, logfile = [16]split.groups.txt)
.SH SYNOPSIS
\fIsplit.groups(fasta, group, logfile = [16]split.groups.txt)\fR
.SH OPTIONS
.PP
\fBfasta\fB \fR\- . 
.PP
.PP
\fBgroup\fB \fR\- . 
.PP
.PP
\fBlogfile\fB \fR\- [16]split.groups.txt. 
.PP
.SH DETAILS
.PP
The split.groups command reads a list, fasta, flow or fastq file and count and generates a list, fasta, flow or fastq files for each group in the count file.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.split.groups at mothur.R:line 428
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2022
