.TH SUMMARY.TAX 1 2022-05-07 "" "taxonomy summary of the annotation"
.SH NAME
summary.tax \- summary.tax(taxonomy, group, logfile = [15]summary.tax.txt)
.SH SYNOPSIS
\fIsummary.tax(taxonomy, group, logfile = [15]summary.tax.txt)\fR
.SH OPTIONS
.PP
\fBtaxonomy\fB \fR\- . 
.PP
.PP
\fBgroup\fB \fR\- . 
.PP
.PP
\fBlogfile\fB \fR\- [15]summary.tax.txt. 
.PP
.SH DETAILS
.PP
The summary.tax command reads a taxonomy file and an optional name and or group file, and summarizes the taxonomy information.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.summary.tax at mothur.R:line 426
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2022
