.TH SUMMARY.SEQS 1 2021-12-10 "" "The ``summary.seqs`` command will summarize the quality of sequences in an unaligned or aligned fasta-formatted sequence file."
.SH NAME
summary.seqs \- summary.seqs(seqfile, count_table, num_threads = 8, logfile = log.txt)
.SH SYNOPSIS
\fIsummary.seqs(seqfile, count_table, num_threads = 8, logfile = log.txt)\fR
.SH OPTIONS
.PP
\fBseqfile\fB \fR\- . 
.PP
.PP
\fBcount_table\fB \fR\- . 
.PP
.PP
\fBnum_threads\fB \fR\- 8. The processors option enables you to accelerate the summary process by using multiple processors. Default processors=Autodetect number of available processors and use all available.
.PP
.PP
\fBlogfile\fB \fR\- log.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.summary.seqs at mothur.R:line 66
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
