.TH SUMMARY.SEQS 1 2024-Feb "" "The ``summary.seqs`` command will summarize the quality of sequences in an unaligned or aligned fasta-formatted sequence file."
.SH NAME
summary.seqs \- summary.seqs(seqfile, count.table,
    <i>num.threads</i> = <span style='color: green;'>8</span>,
    <i>logfile</i> = log.txt)
.SH SYNOPSIS
\fIsummary.seqs(seqfile, count.table,
    <i>num.threads</i> = <span style='color: green;'>8</span>,
    <i>logfile</i> = log.txt)\fR
.SH OPTIONS
.PP
\fBseqfile\fB \fR\- . 
.PP
.PP
\fBcount.table\fB \fR\- . 
.PP
.PP
\fBnum.threads\fB \fR\- 8. 
.PP
.PP
\fBlogfile\fB \fR\- log.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.summary.seqs at mothur.R:line 112
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
