.TH TAXONOMY_ANNOTATION 1 2022-05-07 "" "Do taxonomy annotation for the OTU contigs"
.SH NAME
taxonomy_annotation \- taxonomy_annotation(work16s)
.SH SYNOPSIS
\fItaxonomy_annotation(work16s)\fR
.SH OPTIONS
.PP
\fBwork16s\fB \fR\- . 
.PP
.SH VALUE
.PP
the 16s raw data processing pipeline final result.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.taxonomy_annotation at taxonomy.R:line 76
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2022
