.TH TAXONOMY_ANNOTATION 1 2021-12-13 "" "Do taxonomy annotation for the OTU contigs"
.SH NAME
taxonomy_annotation \- taxonomy_annotation(work16s, OTU_mapping)
.SH SYNOPSIS
\fItaxonomy_annotation(work16s, OTU_mapping)\fR
.SH OPTIONS
.PP
\fBwork16s\fB \fR\- . 
.PP
.PP
\fBOTU_mapping\fB \fR\- . the blastn search result table.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.taxonomy_annotation at taxonomy.R:line 61
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
