.TH UNIQUE.SEQS 1 2021-11-25 "" "unique.seqs"
.SH NAME
unique.seqs \- unique.seqs(contigs, logfile = [4]unique.seqs.txt)
.SH SYNOPSIS
\fIunique.seqs(contigs, logfile = [4]unique.seqs.txt)\fR
.SH OPTIONS
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBlogfile\fB \fR\- [4]unique.seqs.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.unique.seqs at mothur.R:line 143
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
