.TH UNIQUE.SEQS 1 2024-Feb "" "The unique.seqs command returns only the unique sequences found in a fasta-formatted sequence file and a file that indicates those sequences that are identical to the reference sequence. Often times a collection of sequences will have a significant number of identical sequences. It sucks up considerable processing time to have to align, calculate distances, and cluster each of these sequences individually."
.SH NAME
unique.seqs \- unique.seqs(contigs,
    <i>logfile</i> = [4]unique.seqs.txt)
.SH SYNOPSIS
\fIunique.seqs(contigs,
    <i>logfile</i> = [4]unique.seqs.txt)\fR
.SH OPTIONS
.PP
\fBcontigs\fB \fR\- . 
.PP
.PP
\fBlogfile\fB \fR\- [4]unique.seqs.txt. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.unique.seqs at mothur.R:line 190
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
