.TH WORKFLOW2 1 2022-05-07 "" "workflow2"
.SH NAME
workflow2 \- workflow2(refalign, outputdir = ./, num_threads = 8, disable_cache = FALSE)
.SH SYNOPSIS
\fIworkflow2(refalign, outputdir = ./, num_threads = 8, disable_cache = FALSE)\fR
.SH OPTIONS
.PP
\fBrefalign\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBnum_threads\fB \fR\- 8. 
.PP
.PP
\fBdisable_cache\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workflow2 at workflow2.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2022
