.TH WORKFLOW2 1 2024-Feb "" "workflow2"
.SH NAME
workflow2 \- workflow2(refalign,
    <i>outputdir</i> = ./,
    <i>num.threads</i> = <span style='color: green;'>8</span>,
    <i>disable.cache</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIworkflow2(refalign,
    <i>outputdir</i> = ./,
    <i>num.threads</i> = <span style='color: green;'>8</span>,
    <i>disable.cache</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBrefalign\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.PP
\fBnum.threads\fB \fR\- 8. 
.PP
.PP
\fBdisable.cache\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.workflow2 at workflow2.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
