.TH WRITE_CONTIG 1 2021-11-25 "" "write_contig"
.SH NAME
write_contig \- write_contig(seqfile)
.SH SYNOPSIS
\fIwrite_contig(seqfile)\fR
.SH OPTIONS
.PP
\fBseqfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.write_contig at mothur.R:line 75
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
