.TH WRITE_CONTIG 1 2021-12-13 "" "Contig file renames"
.SH NAME
write_contig \- write_contig(seqfile, contig.fasta = contig.fasta)
.SH SYNOPSIS
\fIwrite_contig(seqfile, contig.fasta = contig.fasta)\fR
.SH OPTIONS
.PP
\fBseqfile\fB \fR\- . 
.PP
.PP
\fBcontig.fasta\fB \fR\- contig.fasta. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.write_contig at mothur.R:line 42
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2021
